name: ci-wf
on: 
  push: 
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps: 
      - name: Welcome step
        run: echo "welcome to github actions"
      - name: checkout repository
        uses: actions/checkout@v4 

